### ISSUE TITLE
JWT_KEY issue

### ISSUE THREAD

**Issue by gbreeze** [nartc/nest-mean#14]
Hello, I also have some issues with the JWT_KEY key.

My config:
````
export enum Configuration {
    HOST = '192.168.99.101',
    PORT = '27017',
    MONGO_URI = 'mongodb://192.168.99.101:27017',
    JWT_KEY = 'MySecret!123'
}
````

My error:
````
$ npm start

> server@1.0.0 start C:\github\nest-mean\server
> ts-node -r tsconfig-paths/register src/main.ts

WARNING: No configurations found in configuration directory:C:\github\nest-mean\server\config
WARNING: To disable this warning set SUPPRESS_NO_CONFIG_WARNING in the environment.
[Nest] 28264   - 10/02/2019, 4:22 PM   [NestFactory] Starting Nest application...
[Nest] 28264   - 10/02/2019, 4:22 PM   [InstanceLoader] MongooseModule dependencies initialized +22ms
[Nest] 28264   - 10/02/2019, 4:22 PM   [InstanceLoader] HttpModule dependencies initialized +2ms
[Nest] 28264   - 10/02/2019, 4:22 PM   [ExceptionHandler] Configuration property "MySecret!123" is not defined +14ms
Error: Configuration property "MySecret!123" is not defined
    at Config.get (C:\github\nest-mean\server\node_modules\config\lib\config.js:182:11)
    at ConfigurationService.get (C:\github\nest-mean\server\src\shared\configuration\configuration.service.ts:10:37)
    at new JwtStrategy (C:\github\nest-mean\server\src\shared\auth\strategies\jwt-strategy.service.ts:17:48)
    at Injector.instantiateClass (C:\github\nest-mean\server\node_modules\@nestjs\core\injector\injector.js:276:19)
    at callback (C:\github\nest-mean\server\node_modules\@nestjs\core\injector\injector.js:74:41)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at Object.<anonymous> (C:\github\nest-mean\server\node_modules\ts-node\src\bin.ts:158:12)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
````

greetings g.

**Comment by gbreeze** [comment]
lol, changing the enum^^ fail....
